### ISSUE TITLE
Plan to create a 8.x version

### ISSUE THREAD

**Issue by theodorosploumis** [PatternBuilder/pattern-kit#21]
Hi,

I am trying new things with site building in Drupal 8.x and I came to this project. 

First of all is this project active? If so, is there any plans to upgrade it for Drupal 8.x?

Thanks :-)

**Comment by castastrophe** [comment]
Hey there, it's a great question.  This project is being actively used and somewhat actively maintained but it's not tied to any specific CMS.  This is a tool for previewing patterns during development and possibly in the future, serving components via a REST API.

Our team at Red Hat use PatternKit with Drupal 7 currently but there should be no change to my knowledge for it to work with Drupal 8.  The importer module is a different story: https://github.com/PatternBuilder/pattern-builder-drupal

**Comment by castastrophe** [comment]
I'm going to close out this issue since it's not actionable but don't hesitate to reach out if you have additional questions.
